[book]
authors = ["Polkadot Bulletin Team"]
language = "en"
src = "src"
title = "Polkadot Bulletin Chain Documentation"

[output.html]
site-url = "/polkadot-bulletin-chain/docs/"
git-repository-url = "https://github.com/paritytech/polkadot-bulletin-chain"
edit-url-template = "https://github.com/paritytech/polkadot-bulletin-chain/edit/main/docs/book/{path}"
