# https://www.npmjs.com/package/@zombienet/cli
# To run the network, execute the following command:
# POLKADOT_BULLETIN_BINARY_PATH=./target/release/polkadot-bulletin-chain zombienet -p native spawn ./zombienet/bulletin-polkadot-local.toml

[relaychain]
chain = "bulletin-polkadot-local"
default_command = "{{POLKADOT_BULLETIN_BINARY_PATH}}"

[[relaychain.nodes]]
name = "alice"
p2p_port = 10001
rpc_port = 10000
validator = true
args = ["--ipfs-server", "--enable-hop", "--rpc-max-request-size=150", "--rpc-max-response-size=150", "-lruntime=trace,bitswap=trace,sub-libp2p::bitswap=trace,litep2p=trace,litep2p::crypto::noise=debug,hop=debug"]

[[relaychain.nodes]]
name = "bob"
p2p_port = 12347
rpc_port = 12346
validator = true
args = ["--enable-hop", "--rpc-max-request-size=150", "--rpc-max-response-size=150", "-lruntime=trace,bitswap=trace,sub-libp2p::bitswap=trace,litep2p=trace,litep2p::crypto::noise=debug,hop=debug"]
