# https://www.npmjs.com/package/@zombienet/cli
# To run the network, execute the following command:
# zombienet -p native spawn ./zombienet/config.toml

[relaychain]
chain = "local"
default_command = "{{POLKADOT_BULLETIN_BINARY_PATH}}"

[[relaychain.nodes]]
name = "alice"
rpc_port = 10000
p2p_port = 37999
validator = true
args = ["--ipfs-server", "--enable-hop", "--rpc-max-request-size=150", "--rpc-max-response-size=150", "-lruntime=trace,xcm=trace,hop=debug"]

[[relaychain.nodes]]
name = "bob"
rpc_port = 10001
validator = true
args = ["--enable-hop", "--rpc-max-request-size=150", "--rpc-max-response-size=150", "-lruntime=trace,hop=debug"]
