name: Integration Tests

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Cancel previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 22

jobs:
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    timeout-minutes: 200

    steps:
      - name: Free Disk Space (Ubuntu)
        if: ${{ runner.environment == 'github-hosted' }}
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
        with:
          tool-cache: false

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
          components: rust-src

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler libclang-dev

      - name: Rust cache (Bulletin)
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: .
          shared-key: "bulletin-cache-bulletin-integration-tests"
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Rust cache (Polkadot-SDK)
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: ~/local_bulletin_testing/polkadot-sdk
          shared-key: "bulletin-cache-polkadot-sdk-integration-tests"
          save-if: true
          add-job-id-key: false
          # TODO: change before merging to main
          # save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: examples/package.json

      - name: Install just
        run: cargo install just --locked || true

      - name: Download zombienet
        run: |
          curl -L \
            -H "Authorization: token ${{ github.token }}" \
            -o zombienet-linux-x64 \
            "https://github.com/paritytech/zombienet/releases/download/v1.3.138/zombienet-linux-x64"
          chmod +x zombienet-linux-x64
          echo "ZOMBIENET_BINARY=$GITHUB_WORKSPACE/zombienet-linux-x64" >> $GITHUB_ENV

      - name: Run authorize and store (PAPI, smoldot, Polkadot solochain)
        working-directory: examples
        run: just run-authorize-and-store "smoldot" "bulletin-polkadot-runtime"

      - name: Run authorize and store (PAPI, RPC node, Westend parachain)
        working-directory: examples
        run: just run-authorize-and-store "ws" "bulletin-westend-runtime"

      - name: Run store chunked data + DAG-PB (PJS-API, RPC node, Polkadot solochain)
        working-directory: examples
        run: just run-store-chunked-data "bulletin-polkadot-runtime"

      # Collects logs from the last failed zombienet run.
      - name: Upload Zombienet logs (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: failed-zombienet-logs
          path: |
            /tmp/bulletin-tests-run/*.log
